import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { ThemeProvider } from './components/theme-provider'
import Navbar from "./components/navbar";
import Footer from "./components/footer";
import Menu from './components/menu';
import { ClerkProvider } from '@clerk/nextjs';


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Blog App Abbas Ali Kazmi',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider>
    <html lang="en">
      <body className={inter.className}>
      <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
          <Navbar/>
          <Menu/>
          <main className="max-w-2xl mx-auto px-4 ">{children}</main>

          <Footer/>
          </ThemeProvider>
          </body>
    </html>
    </ClerkProvider>
  )
}
